Added option to hide Discord Shop button
BleedingBD/plugin-RemoveChatButtons pull request #17
Opened 2023-11-04 23:34 UTC by LancersBucket

- Added ability to disable Discord Shop button and added config setting.
- Closes #15

2023-12-28 22:42 UTC, 7MXek commented
I'm eagerly awaiting this merge request to be approved. @QbDesu, is this plugin still being maintained?

2024-05-18 11:18 UTC, deepspaceaxolotl commented
I would also like to know when this will be approved.

2024-06-01 18:58 UTC, MagmaBro123 commented
If this plugin is dead, please remove it. If it isn't, please merge this.

2024-06-03 14:24 UTC, 7MXek commented
> If this plugin is dead, please remove it. If it isn't, please merge this.

There has been absolutely no activity for over a year. I think we're going to need someone to fork the repository.

2024-06-29 07:49 UTC, whataboutism-alos commented
please 🙏

2024-07-19 08:58 UTC, Ecconia requested changes
Dead repo - random guy reviews :P
(Thanks for this PR, swiftly applied it locally).

2024-07-19 08:58 UTC, Ecconia commented on RemoveChatButtons.plugin.js
> +                    }
There should be a trailing comma here to maintain the file style (and keep future additions clean).

2024-07-19 16:11 UTC, MagmaBro123 commented
> Dead repo - random guy reviews :P (Thanks for this PR, swiftly applied it locally).

Then you should fork and continue this yourself.

2024-09-01 01:57 UTC, closed without merging